#Create a docker image with nextjs with node 16.20 with nginx

FROM node:16.20.0

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

RUN npm install

# Bundle app source

COPY . .

RUN npm run build

EXPOSE 3000

CMD [ "npm", "start" ]

